version: '3.5'
services:
  dbpat:
    container_name: dbpat
    command: postgres -c 'max_connections=200'
    image: postgres:12
    hostname: dbpat
    restart: always
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=dbpat
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./pat_data:/var/lib/postgresql/data
    networks:
     - tp-ads
networks:
    tp-ads:
      name: tp-ads